# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               adam gilman
tagline:             'welcome to this'
description:         'ruminations, projects, and random thoughts of <a href="http://twitter.com/adamgilman">@adamgilman</a>'
url:                 http://adamgilman.com
baseurl:             ''
paginate:            5

gems: [jekyll-paginate]

# About/contact
author:
  name:              Adam Gilman
  url:               https://twitter.com/adamgilman
  email:             me@adamgilman.com
